#!/bin/bash

show_usage="args:[-i ip -p port -u user -a password -d description]"


ip=""
port=""
pass=""
user=""
des=""

while [ -n "$1" ]
do
        case "$1" in
                -i) ip=$2; shift 2;;
                -p) port=$2; shift 2;;
                -u) user=$2; shift 2;;
                -a) pass=$2; shift 2;;
                -d) des=$2; shift 2;;
                *) echo $show_usage; exit 2;;
        esac
done

if [[ $ip != "" ]]; then
  if [[ $des == "" ]]; then
    read -p "Input the description:" des
  fi
  if [[ $user == "" ]]; then
    read -p "Input the username:" user
  fi
  if [[ $pass == "" ]]; then
    read -p "Input the password:" pass
  fi
  if [[ $port == "" ]]; then
    read -p "Input the port(defalut 22):" port
  fi
  if [[ $port == "" ]]; then
    port="22"
  fi
  command="asshp ad "$ip" "$port" "$pass" "$user" "$des
  re=`$command`
  sshlog $ip $port $user $pass
else
  if [[ $des != "" ]]; then
    #调用python脚本获取信息登录
    da=`asshp.py sr $des`
    ip=`echo $da | awk '{print $1}'`
    port=`echo $da | awk '{print $2}'`
    pass=`echo $da | awk '{print $3}'`
    user=`echo $da | awk '{print $4}'`
    sshlog $ip $port $user $pass
  else
    echo "Please input ip or description"
    exit 2
  fi
fi
